# Generated by Django 4.2.1 on 2023-06-12 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_management', '0001_initial'),
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('number_tags', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('model', models.TextField()),
                ('wifi_firmware_version', models.CharField(max_length=255)),
                ('bluetooth_firmware_version', models.CharField(max_length=255)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_management.store')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.FileField(upload_to='qr_codes')),
                ('battery', models.FloatField()),
                ('mac_address', models.TextField()),
                ('price', models.FloatField()),
                ('tag_template', models.ImageField(upload_to='tag_templates')),
                ('tva', models.FloatField(default=0.19)),
                ('current_quantity', models.FloatField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_management.product')),
                ('promo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_management.promo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_management.store')),
            ],
        ),
    ]
